    <footer class="ak-container ak-footer">

        <div class="first-footer">

            <div class="container-fluid">

                <div class="row">
                    <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3">
                        <a href="#">
                            <img src="./assets/f-logo.svg" alt="Al Kenz Pharmaceutical">
                        </a>
                    </div>
                    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 flex-center">
                        <ul class="footer-navbar">
                            <li>About Us</li>
                            <li>Our Team</li>
                            <li>Partners</li>
                            <li>Products</li>
                            <li>Insights</li>
                            <li>Services</li>
                        </ul>
                    </div>
                    <div class="col-sm-12 col-md-3 col-lg-3 col-xl-3 flex-end">
                        <ul class="footer-navbar">
                            <li>
                                <div class="social-link">
                                    <img src="./assets/icons/fb.svg" alt="">
                                </div>
                            </li>
                            <li>
                                <div class="social-link">
                                    <img src="./assets/icons/insta.svg" alt="">
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            
        </div>
        <div class="second-footer">
            
            <div class="container-fluid">

                <div class="row">
                    <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <div class="copyright">Copyright © 2024 - Al Kanz Pharmaceutical Products</div>
                    </div>
                    <div class="col-sm-12 col-md-8 col-lg-8 col-xl-8">

                        <ul class="bottombar-list fr">
                            <li class="phone separator">
                                <img src="./assets/icons/phone.svg" alt="Phone">
                                <span>+971 428 2230</span>
                            </li>
                            <li class="email separator">
                                <img src="./assets/icons/mail.svg" alt="Email">
                                <span>info@alkenz.com</span>
                            </li>
                            <li class="address">
                                <img src="./assets/icons/map.svg" alt="Address">
                                <span>Office No.74, Al Habtoor Warehouse Ind. Area 3, Al Qusais, Dubai, UAE</span>
                            </li>
                        </ul>
                        
                    </div>
                </div>

            </div>

        </div>
        
    </footer>